### PR TITLE
Add code coverage tooling and Coveralls workflow

### PR DESCRIPTION
**Pull request by jackson-at-bentley**
### $ npm run test:standalone

coverage

I chose `nyc` because other projects at Bentley like `ecschema2ts` use it. If I configured everything correctly, the synchronizer has about 40 percent line coverage.

~~This is a breaking PR, but I don't think any projects depend on the v3 `@itwin/connector-framework` yet.~~ I've reverted the breaking API change in #45, which I'm closing because I can't run the Azure pipeline on the fork. My "fix" is hardcoding the path to the test connector's schema, because `__dirname`'s value in `KnownTestLocations` changes when running JIT with `ts-node` and when being `require`'ed.

- I installed [`mocha-suppress-logs`](https://www.npmjs.com/package/mocha-suppress-logs) to suppress the [`Logger`](https://www.itwinjs.org/reference/core-bentley/logging/logger/) output.
- I rearranged the project structure to make `mocha` happy. `test` is now in the root directory.
- I added a Coveralls GitHub workflow. If Jason is okay with giving me the keys 🔑 to the repository for a day I'd like to finish setting it up (authenticating with Coveralls and adding the Coveralls account as a collaborator so it can leave coverage comments).

### To address

- [x] The HTML reporter fails to correctly link to the source files. I've opened [an issue](https://github.com/istanbuljs/nyc/issues/1475) on `nyc`, but the text reporter works as shown above. (I've downgraded `ts-node`.)
- [x] `npm run test:connector` is failing with `fetch is not defined`. That code hasn't changed, and isn't covered by the tests [Figure 1].
- [x]  `npm run test:integration` is failing _only on Linux_ with `Failed OIDC signin. Looks like something is not right. Please contact your administrator. 400 - Invalid client_id`. There's this very suspicious comment in `oicd-signin-tool` [Figure 2]. This also happens on the `main` branch on Linux.
- [ ] We shouldn't need to compile everything in the `test` directory because of the `ts-node` JIT tooling, but I'm not sure how else to configure `nyc`, because parts of that directory need to be compiled.

I've never configured coverage tooling before so I welcome any and all feedback.

### What's next

- [ ] I'd like to add coverage standards to our integration, and maybe a service like [`coveralls`](https://coveralls.io/) for visibility.

### Figures

Figure 1

fetch

Figure 2

```javascript
// Launch puppeteer with no sandbox only on linux
let launchOptions = { dumpio: true }; // , headless: false, slowMo: 500 };
if (os.platform() === "linux") {
    launchOptions = {
        args: ["--no-sandbox"], // , "--disable-setuid-sandbox"],
    };
}
````

### CODE REVIEW

**Comment by jackson-at-bentley** [comment]
@jchick-bentley I was enjoying the imagery of joyriding the repository around. Here's the steps I took on my fork to get Coveralls working.

1. Sign us up for [Coveralls](https://coveralls.io/sign-up).
2. Follow the steps [in the GitHub actions README](https://github.com/marketplace/actions/coveralls-github-action#troubleshooting).
    1. You have invited the [@coveralls](https://github.com/coveralls) user to your repository as a collaborator
    2. You have enabled the "LEAVE COMMENTS?" setting in the "Pull Request Alerts" area in your Repo Settings page inside the Coveralls app.

**Comment by jchick-bentley** [comment]
> @jchick-bentley I was enjoying the imagery of joyriding the repository around. Here's the steps I took on my fork to get Coveralls working.
> 
> 1. Sign us up for [Coveralls](https://coveralls.io/sign-up).
> 2. Follow the steps [in the GitHub actions README](https://github.com/marketplace/actions/coveralls-github-action#troubleshooting).
>    
>    1. You have invited the [@coveralls](https://github.com/coveralls) user to your repository as a collaborator
>    2. You have enabled the "LEAVE COMMENTS?" setting in the "Pull Request Alerts" area in your Repo Settings page inside the Coveralls app.

Ok - let's complete this PR w/o taking those extra steps.  Seems like I have to grant access to all of iTwin rather than just our repo that's using it.  I'll seek approval from someone who can speak for all of iTwin.

**Comment by jchick-bentley** [comment]
> > @jchick-bentley I was enjoying the imagery of joyriding the repository around. Here's the steps I took on my fork to get Coveralls working.
> > 
> > 1. Sign us up for [Coveralls](https://coveralls.io/sign-up).
> > 2. Follow the steps [in the GitHub actions README](https://github.com/marketplace/actions/coveralls-github-action#troubleshooting).
> >    
> >    1. You have invited the [@coveralls](https://github.com/coveralls) user to your repository as a collaborator
> >    2. You have enabled the "LEAVE COMMENTS?" setting in the "Pull Request Alerts" area in your Repo Settings page inside the Coveralls app.
> 
> Ok - let's complete this PR w/o taking those extra steps. Seems like I have to grant access to all of iTwin rather than just our repo that's using it. I'll seek approval from someone who can speak for all of iTwin.

@akshay-madhukar @admccarthy1 can we please get one more reviewer before we merge?

**Review by admccarthy1 — APPROVED** [review]

**Comment by admccarthy1** [comment]
sorry about the delay, I didn't see the email this morning because my internet is out (again) but looks good to me.

**Pull request merged**
